# Site settings
title: Foobot Technical Blog 
email: hello@foobot.io
description: > # this means to ignore newlines until "baseurl:"
  The guys behind Foobot. Talking here about our achievements, failures & OSS contributions
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://airboxlab.github.io/" # the base hostname & protocol for your site
twitter_username: myfoobot
github_username:  airboxlab

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag

collections:
  drafts: 
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

defaults:
  - scope:
      path: ""
      type: drafts
    values:
      comments: false
      share: false
      related: false
      sitemap: false  #To hide from sitemap.xml
      noindex: true   #To hide from robots and crawlers