# Site settings
title: Airboxlab Technical Blog 
email: hello@airboxlab.com
description: > # this means to ignore newlines until "baseurl:"
  The guys behind Foobot.Talking here about our achievements, failures & OSS contributions
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://airboxlab.github.io/" # the base hostname & protocol for your site
twitter_username: myfoobot
github_username:  airboxlab

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
