# Site settings
title: Airboxlab Technical Blog 
email: info@airboxlab.com
description: > # this means to ignore newlines until "baseurl:"
  Airboxlab technical blog, talking about our achievements, our fails, our OSS contributions, ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://airboxlab.github.io/" # the base hostname & protocol for your site
twitter_username: Airboxlab
github_username:  airboxlab

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
